[project]
name = "contract"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet

[repl.analysis]
passes = []

[contracts]

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
clarity_version = 4
epoch = "latest"

[contracts.snake-score]
path = "contracts/snake-score.clar"
clarity_version = 4
epoch = "latest"

[contracts.tetris-score]
path = "contracts/tetris-score.clar"
clarity_version = 4
epoch = "latest"

[contracts.pacman-score]
path = "contracts/pacman-score.clar"
clarity_version = 4
epoch = "latest"

[contracts.breakout-score]
path = "contracts/breakout-score.clar"
clarity_version = 4
epoch = "latest"
